### ISSUE TITLE
Rethink if fields should be sorted alphabetically or have a fixed order

### ISSUE THREAD

**Issue by jorinvo** [ratlog/ratlog.github.io#10]
I am not sure about this part myself yet. Currently the spec states that sorting is not enforced:

    The sorting of tags may be user-defined and may be relevant.

https://github.com/ratlog/ratlog.github.io#tags

If it's not enforced, it is kind of difficult to build predictable tests and other problems. But on the other hand it is also nice if you can sort fields in a logical way instead of alphabetical order.

If the order is relevant, the fields in the test suite should probably look more like one of these:

```json
"fields": [{ "event": "one" }, { "count": "1" }]
"fields": [["event", "one" ], ["count", "1" ]]
```

A possible issue with using an alphabetical sort order is that there are many edge cases with sorting things that are not simply ascii letters.

Any thoughts or preferences?

**Comment by alxwrd** [comment]
Sorry, I'm a bit confused, and just want to make sure we're talking about the same thing? The section on fields says
> The sorting of fields is not relevant and may be ignored. It is recommended to sort fields alphabetically.
> _https://github.com/ratlog/ratlog.github.io#fields_

---
I think that nicest user experience approach would be if the fields (and maybe tags) are displayed in the order they're entered, as I think this would make the most sense when viewing logs, and allows the entries to be ordered in any way. E.g.

```javascript
log('log', { a: 1 , b: 2})
// => log | a: 1 | b: 2

log('log', { b: 2 , a: 1})
// => log | b: 2 | a: 1
```

However, this poses a problem for a Python implementation because of the issue with unordered dictionaries.

**Comment by jorinvo** [comment]
Had no further issues with this. The spec is marked as stable now and I think the current decision is the most practical – don't enforce any sort order and let each language us its own variant of a hashmap. Yes, this makes the testsuite a bit harder to use, but we should not compromise the simplicity of the spec to simplify the testsuite.
